/**
 * Created by phuongnguyen on 12/03/16.
 */
connection coming..... Socket {
    _connecting: false,
        _hadError: false,
        _handle:
    TCP {
        _externalStream: {},
        fd: 24,
            reading: false,
            owner: [Circular],
            onread: [Function: onread],
        onconnection: null,
            writeQueueSize: 0 },
    _parent: null,
        _host: null,
        _readableState:
    ReadableState {
        objectMode: false,
            highWaterMark: 16384,
            buffer: [],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: false,
            ended: false,
            endEmitted: false,
            reading: false,
            sync: true,
            needReadable: false,
            emittedReadable: false,
            readableListening: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null },
    readable: true,
        domain: null,
        _events:
    { end: { [Function: g] listener: [Function: onend] },
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd] },
    _eventsCount: 3,
        _maxListeners: undefined,
        _writableState:
    WritableState {
        objectMode: false,
            highWaterMark: 16384,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: true,
            bufferProcessing: false,
            onwrite: [Function],
            writecb: null,
            writelen: 0,
            bufferedRequest: null,
            lastBufferedRequest: null,
            pendingcb: 0,
            prefinished: false,
            errorEmitted: false },
    writable: true,
        allowHalfOpen: false,
        destroyed: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server:
    Server {
        domain: null,
            _events: { connection: [Object] },
        _eventsCount: 1,
            _maxListeners: undefined,
            _connections: 1,
            _handle:
        TCP {
            _externalStream: {},
            fd: 22,
                reading: false,
                owner: [Circular],
                onread: null,
                onconnection: [Function],
                writeQueueSize: 0 },
        _usingSlaves: false,
            _slaves: [],
            _unref: false,
            allowHalfOpen: false,
            pauseOnConnect: true,
            _connectionKey: '6::::8181' } } 4
